name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Pre-Req. - Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Deps - Install dependencies
      run: poetry install
    - name: Build - Python Package
      run: poetry build
    - name: System - run App (entrypoint)
      run: poetry run app
    - uses: ncipollo/release-action@v1
      with:
        # Store both the Python Wheel + generated renderings on Release page.
        artifacts: "dist/*.*,build/output/*.*"
        token: ${{ secrets.GITHUB_TOKEN }}
